title: Lakindu S. Pathira Kankanamge
#logo: path to figure
description: Dedicated molecular biologist with a proven track record of 10+ yeares in conducting innovative research in academia and industrial scientific settings with more than 15+ research publications. Proficient in molecular techniques, genetic manipulation, and data analysis. Skilled in experimental design, execution, and interpretation, with a strong commitment to advancing scientific knowledge and contributing to breakthrough discoveries in the field
show_downloads: true
theme: jekyll-theme-minimal
